/**
 * Seed curated universities into Firestore.
 *
 * Usage:  pnpm seed:universities        (from apps/worker)
 *         pnpm --filter @edlight-news/worker seed:universities
 *
 * Upserts by name+country so reruns are idempotent.
 */

import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import { universitiesRepo } from "@edlight-news/firebase";
import type { CreateUniversity } from "@edlight-news/types";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const monorepoRoot = path.resolve(__dirname, "../../../..");
dotenv.config({ path: path.resolve(monorepoRoot, ".env") });

// ── Seed data ──────────────────────────────────────────────────────────────

const UNIVERSITIES: CreateUniversity[] = [
  // ── US: Ivy League ─────────────────────────────────────────────────────
  {
    name: "Harvard University",
    country: "US",
    city: "Cambridge, MA",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://college.harvard.edu/admissions",
    internationalAdmissionsUrl: "https://college.harvard.edu/admissions/apply/international-applicants",
    scholarshipUrl: "https://college.harvard.edu/financial-aid",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App" },
    haitianFriendly: true,
    tags: ["ivy-league", "need-blind"],
    sources: [{ url: "https://college.harvard.edu/admissions", label: "Harvard Admissions" }],
  },
  {
    name: "Columbia University",
    country: "US",
    city: "New York, NY",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://undergrad.admissions.columbia.edu/",
    internationalAdmissionsUrl: "https://undergrad.admissions.columbia.edu/apply/international-students",
    scholarshipUrl: "https://cc-seas.financialaid.columbia.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App / Coalition" },
    haitianFriendly: true,
    tags: ["ivy-league", "need-blind"],
    sources: [{ url: "https://undergrad.admissions.columbia.edu/", label: "Columbia Admissions" }],
  },
  {
    name: "Yale University",
    country: "US",
    city: "New Haven, CT",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admissions.yale.edu/",
    internationalAdmissionsUrl: "https://admissions.yale.edu/international-applicants",
    scholarshipUrl: "https://finaid.yale.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App / QuestBridge" },
    haitianFriendly: true,
    tags: ["ivy-league", "need-blind"],
    sources: [{ url: "https://admissions.yale.edu/", label: "Yale Admissions" }],
  },
  {
    name: "Princeton University",
    country: "US",
    city: "Princeton, NJ",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admission.princeton.edu/",
    internationalAdmissionsUrl: "https://admission.princeton.edu/apply/international-students",
    scholarshipUrl: "https://admission.princeton.edu/financial-aid",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "Common App / QuestBridge" },
    haitianFriendly: true,
    tags: ["ivy-league", "need-blind"],
    sources: [{ url: "https://admission.princeton.edu/", label: "Princeton Admissions" }],
  },
  {
    name: "University of Pennsylvania",
    country: "US",
    city: "Philadelphia, PA",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admissions.upenn.edu/",
    internationalAdmissionsUrl: "https://admissions.upenn.edu/admissions-and-financial-aid/international-applicants",
    scholarshipUrl: "https://srfs.upenn.edu/financial-aid",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App" },
    tags: ["ivy-league", "need-blind"],
    sources: [{ url: "https://admissions.upenn.edu/", label: "UPenn Admissions" }],
  },
  {
    name: "Brown University",
    country: "US",
    city: "Providence, RI",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admission.brown.edu/",
    internationalAdmissionsUrl: "https://admission.brown.edu/apply/international-students",
    scholarshipUrl: "https://financialaid.brown.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App / QuestBridge" },
    tags: ["ivy-league"],
    sources: [{ url: "https://admission.brown.edu/", label: "Brown Admissions" }],
  },
  {
    name: "Dartmouth College",
    country: "US",
    city: "Hanover, NH",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admissions.dartmouth.edu/",
    internationalAdmissionsUrl: "https://admissions.dartmouth.edu/apply/international-applicants",
    scholarshipUrl: "https://financialaid.dartmouth.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App / QuestBridge" },
    tags: ["ivy-league", "need-blind"],
    sources: [{ url: "https://admissions.dartmouth.edu/", label: "Dartmouth Admissions" }],
  },
  {
    name: "Cornell University",
    country: "US",
    city: "Ithaca, NY",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admissions.cornell.edu/",
    internationalAdmissionsUrl: "https://admissions.cornell.edu/apply/international-first-year-applicants",
    scholarshipUrl: "https://finaid.cornell.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App" },
    tags: ["ivy-league"],
    sources: [{ url: "https://admissions.cornell.edu/", label: "Cornell Admissions" }],
  },

  // ── US: Flagship state universities ────────────────────────────────────
  {
    name: "University of Florida",
    country: "US",
    city: "Gainesville, FL",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://admissions.ufl.edu/",
    internationalAdmissionsUrl: "https://admissions.ufl.edu/apply/international/",
    scholarshipUrl: "https://www.sfa.ufl.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "Coalition / Common App" },
    haitianFriendly: true,
    tags: ["flagship", "haitian-diaspora"],
    sources: [{ url: "https://admissions.ufl.edu/", label: "UF Admissions" }],
  },
  {
    name: "Florida International University",
    country: "US",
    city: "Miami, FL",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://admissions.fiu.edu/",
    internationalAdmissionsUrl: "https://admissions.fiu.edu/how-to-apply/international/",
    scholarshipUrl: "https://onestop.fiu.edu/finances/types-of-aid/scholarships/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["flagship", "haitian-diaspora", "creole-programs"],
    sources: [{ url: "https://admissions.fiu.edu/", label: "FIU Admissions" }],
  },
  {
    name: "University of Michigan",
    country: "US",
    city: "Ann Arbor, MI",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admissions.umich.edu/",
    internationalAdmissionsUrl: "https://admissions.umich.edu/apply/first-year-applicants/international-applicants",
    scholarshipUrl: "https://finaid.umich.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Common App / Coalition" },
    tags: ["flagship"],
    sources: [{ url: "https://admissions.umich.edu/", label: "UMich Admissions" }],
  },
  {
    name: "University of California, Berkeley",
    country: "US",
    city: "Berkeley, CA",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://admissions.berkeley.edu/",
    internationalAdmissionsUrl: "https://admissions.berkeley.edu/international-applicants/",
    scholarshipUrl: "https://financialaid.berkeley.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "UC Application" },
    tags: ["flagship", "uc-system"],
    sources: [{ url: "https://admissions.berkeley.edu/", label: "Berkeley Admissions" }],
  },
  {
    name: "Massachusetts Institute of Technology",
    country: "US",
    city: "Cambridge, MA",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://mitadmissions.org/",
    internationalAdmissionsUrl: "https://mitadmissions.org/apply/process/international-applicants/",
    scholarshipUrl: "https://sfs.mit.edu/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "MIT Application" },
    tags: ["stem", "need-blind"],
    sources: [{ url: "https://mitadmissions.org/", label: "MIT Admissions" }],
  },

  // ── Canada: Top 15 ────────────────────────────────────────────────────
  {
    name: "Université de Montréal",
    country: "CA",
    city: "Montréal, QC",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://admission.umontreal.ca/",
    internationalAdmissionsUrl: "https://admission.umontreal.ca/admission/etudiants-etrangers/",
    scholarshipUrl: "https://bourses.umontreal.ca/",
    requirements: { frenchTests: ["TCF", "TEF", "DELF/DALF"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["francophone", "quebec"],
    sources: [{ url: "https://admission.umontreal.ca/", label: "UdeM Admissions" }],
  },
  {
    name: "Université Laval",
    country: "CA",
    city: "Québec, QC",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.ulaval.ca/admission",
    internationalAdmissionsUrl: "https://www.ulaval.ca/admission/etudiants-etrangers",
    scholarshipUrl: "https://www.bbaf.ulaval.ca/",
    requirements: { frenchTests: ["TCF", "TEF", "DELF/DALF"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["francophone", "quebec"],
    sources: [{ url: "https://www.ulaval.ca/admission", label: "ULaval Admissions" }],
  },
  {
    name: "McGill University",
    country: "CA",
    city: "Montréal, QC",
    languages: ["en", "fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.mcgill.ca/undergraduate-admissions/",
    internationalAdmissionsUrl: "https://www.mcgill.ca/undergraduate-admissions/apply/international",
    scholarshipUrl: "https://www.mcgill.ca/studentaid/scholarships-aid",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], frenchTests: ["TCF"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["bilingual", "quebec"],
    sources: [{ url: "https://www.mcgill.ca/undergraduate-admissions/", label: "McGill Admissions" }],
  },
  {
    name: "University of Toronto",
    country: "CA",
    city: "Toronto, ON",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.utoronto.ca/admissions",
    internationalAdmissionsUrl: "https://future.utoronto.ca/apply/international-applicants/",
    scholarshipUrl: "https://future.utoronto.ca/finances/scholarships/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "OUAC" },
    tags: ["anglophone"],
    sources: [{ url: "https://www.utoronto.ca/admissions", label: "UofT Admissions" }],
  },
  {
    name: "University of British Columbia",
    country: "CA",
    city: "Vancouver, BC",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://you.ubc.ca/applying-ubc/",
    internationalAdmissionsUrl: "https://you.ubc.ca/applying-ubc/international/",
    scholarshipUrl: "https://students.ubc.ca/enrolment/finances/awards-scholarships-bursaries",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Direct" },
    tags: ["anglophone"],
    sources: [{ url: "https://you.ubc.ca/applying-ubc/", label: "UBC Admissions" }],
  },
  {
    name: "Université du Québec à Montréal",
    country: "CA",
    city: "Montréal, QC",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://admission.uqam.ca/",
    internationalAdmissionsUrl: "https://international.uqam.ca/etudiant-international/",
    scholarshipUrl: "https://bourses.uqam.ca/",
    requirements: { frenchTests: ["TCF", "TEF", "DELF/DALF"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["francophone", "quebec", "affordable"],
    sources: [{ url: "https://admission.uqam.ca/", label: "UQAM Admissions" }],
  },
  {
    name: "Université de Sherbrooke",
    country: "CA",
    city: "Sherbrooke, QC",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.usherbrooke.ca/admission/",
    internationalAdmissionsUrl: "https://www.usherbrooke.ca/admission/futur-etudiant/international/",
    scholarshipUrl: "https://www.usherbrooke.ca/bourses/",
    requirements: { frenchTests: ["TCF", "TEF", "DELF/DALF"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["francophone", "quebec", "co-op"],
    sources: [{ url: "https://www.usherbrooke.ca/admission/", label: "UdeS Admissions" }],
  },
  {
    name: "Concordia University",
    country: "CA",
    city: "Montréal, QC",
    languages: ["en", "fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.concordia.ca/admissions.html",
    internationalAdmissionsUrl: "https://www.concordia.ca/admissions/international.html",
    scholarshipUrl: "https://www.concordia.ca/offices/faao/scholarships-awards.html",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["bilingual", "quebec"],
    sources: [{ url: "https://www.concordia.ca/admissions.html", label: "Concordia Admissions" }],
  },
  {
    name: "University of Ottawa",
    country: "CA",
    city: "Ottawa, ON",
    languages: ["en", "fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.uottawa.ca/undergraduate-admissions/",
    internationalAdmissionsUrl: "https://www.uottawa.ca/undergraduate-admissions/international-students",
    scholarshipUrl: "https://www.uottawa.ca/financial-aid-awards/",
    requirements: { englishTests: ["TOEFL", "IELTS"], frenchTests: ["TCF", "TEF"], applicationPlatform: "OUAC" },
    haitianFriendly: true,
    tags: ["bilingual", "ontario"],
    sources: [{ url: "https://www.uottawa.ca/undergraduate-admissions/", label: "UOttawa Admissions" }],
  },
  {
    name: "University of Alberta",
    country: "CA",
    city: "Edmonton, AB",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.ualberta.ca/admissions/",
    internationalAdmissionsUrl: "https://www.ualberta.ca/admissions/international/",
    scholarshipUrl: "https://www.ualberta.ca/registrar/scholarships-awards-financial-support/",
    requirements: { englishTests: ["TOEFL", "IELTS", "DET"], applicationPlatform: "Direct" },
    tags: ["anglophone"],
    sources: [{ url: "https://www.ualberta.ca/admissions/", label: "UAlberta Admissions" }],
  },

  // ── France: Campus France + top universities ──────────────────────────
  {
    name: "Université Paris-Saclay",
    country: "FR",
    city: "Gif-sur-Yvette",
    languages: ["fr", "en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.universite-paris-saclay.fr/admission",
    internationalAdmissionsUrl: "https://www.universite-paris-saclay.fr/admission/etudiants-internationaux",
    scholarshipUrl: "https://www.universite-paris-saclay.fr/bourses",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    haitianFriendly: true,
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.universite-paris-saclay.fr/admission", label: "Paris-Saclay Admissions" }],
  },
  {
    name: "Sorbonne Université",
    country: "FR",
    city: "Paris",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.sorbonne-universite.fr/formation/admission",
    internationalAdmissionsUrl: "https://www.sorbonne-universite.fr/formation/admission/candidature-internationale",
    scholarshipUrl: "https://www.sorbonne-universite.fr/vie-etudiante/bourses",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    haitianFriendly: true,
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.sorbonne-universite.fr/formation/admission", label: "Sorbonne Admissions" }],
  },
  {
    name: "Université PSL (Paris Sciences & Lettres)",
    country: "FR",
    city: "Paris",
    languages: ["fr", "en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://psl.eu/formation/admission",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], englishTests: ["TOEFL", "IELTS"], applicationPlatform: "Campus France / Direct" },
    tags: ["campus-france", "public", "excellence"],
    sources: [{ url: "https://psl.eu/formation/admission", label: "PSL Admissions" }],
  },
  {
    name: "Université de Strasbourg",
    country: "FR",
    city: "Strasbourg",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.unistra.fr/formation/admission",
    internationalAdmissionsUrl: "https://www.unistra.fr/international/etudiants-internationaux",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    haitianFriendly: true,
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.unistra.fr/formation/admission", label: "Strasbourg Admissions" }],
  },
  {
    name: "Université de Montpellier",
    country: "FR",
    city: "Montpellier",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.umontpellier.fr/formation/admission",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.umontpellier.fr/formation/admission", label: "Montpellier Admissions" }],
  },
  {
    name: "Sciences Po Paris",
    country: "FR",
    city: "Paris",
    languages: ["fr", "en"],
    levelSupport: ["bachelor", "master"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.sciencespo.fr/admissions/",
    internationalAdmissionsUrl: "https://www.sciencespo.fr/admissions/en/international-students",
    scholarshipUrl: "https://www.sciencespo.fr/students/finances/financial-aid",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], englishTests: ["TOEFL", "IELTS"], applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["grande-ecole", "political-science"],
    sources: [{ url: "https://www.sciencespo.fr/admissions/", label: "Sciences Po Admissions" }],
  },
  {
    name: "Université Grenoble Alpes",
    country: "FR",
    city: "Grenoble",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.univ-grenoble-alpes.fr/formation/admission/",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    tags: ["campus-france", "public", "stem"],
    sources: [{ url: "https://www.univ-grenoble-alpes.fr/formation/admission/", label: "UGA Admissions" }],
  },
  {
    name: "Université de Bordeaux",
    country: "FR",
    city: "Bordeaux",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.u-bordeaux.fr/formation/admission",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.u-bordeaux.fr/formation/admission", label: "Bordeaux Admissions" }],
  },
  {
    name: "Université de Lyon (UCBL)",
    country: "FR",
    city: "Lyon",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.univ-lyon1.fr/formation/admission",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.univ-lyon1.fr/formation/admission", label: "Lyon 1 Admissions" }],
  },
  {
    name: "Aix-Marseille Université",
    country: "FR",
    city: "Marseille",
    languages: ["fr"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.univ-amu.fr/fr/public/admission",
    requirements: { frenchTests: ["TCF", "DELF/DALF"], applicationPlatform: "Campus France / Études en France" },
    tags: ["campus-france", "public"],
    sources: [{ url: "https://www.univ-amu.fr/fr/public/admission", label: "AMU Admissions" }],
  },

  // ── UK: Russell Group ─────────────────────────────────────────────────
  {
    name: "University of Oxford",
    country: "UK",
    city: "Oxford",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.ox.ac.uk/admissions/",
    internationalAdmissionsUrl: "https://www.ox.ac.uk/admissions/undergraduate/international-students/",
    scholarshipUrl: "https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.ox.ac.uk/admissions/", label: "Oxford Admissions" }],
  },
  {
    name: "University of Cambridge",
    country: "UK",
    city: "Cambridge",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.undergraduate.study.cam.ac.uk/",
    internationalAdmissionsUrl: "https://www.undergraduate.study.cam.ac.uk/international-students",
    scholarshipUrl: "https://www.cambridgetrust.org/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.undergraduate.study.cam.ac.uk/", label: "Cambridge Admissions" }],
  },
  {
    name: "Imperial College London",
    country: "UK",
    city: "London",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.imperial.ac.uk/study/apply/",
    internationalAdmissionsUrl: "https://www.imperial.ac.uk/study/apply/undergraduate/international/",
    scholarshipUrl: "https://www.imperial.ac.uk/students/fees-and-funding/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group", "stem"],
    sources: [{ url: "https://www.imperial.ac.uk/study/apply/", label: "Imperial Admissions" }],
  },
  {
    name: "University College London",
    country: "UK",
    city: "London",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.ucl.ac.uk/prospective-students/",
    internationalAdmissionsUrl: "https://www.ucl.ac.uk/prospective-students/international/",
    scholarshipUrl: "https://www.ucl.ac.uk/scholarships/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.ucl.ac.uk/prospective-students/", label: "UCL Admissions" }],
  },
  {
    name: "London School of Economics",
    country: "UK",
    city: "London",
    languages: ["en"],
    levelSupport: ["bachelor", "master"],
    tuitionBand: "high",
    admissionsUrl: "https://www.lse.ac.uk/study-at-lse/",
    internationalAdmissionsUrl: "https://www.lse.ac.uk/study-at-lse/international-students",
    scholarshipUrl: "https://www.lse.ac.uk/study-at-lse/financial-support",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group", "social-sciences"],
    sources: [{ url: "https://www.lse.ac.uk/study-at-lse/", label: "LSE Admissions" }],
  },
  {
    name: "University of Edinburgh",
    country: "UK",
    city: "Edinburgh",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.ed.ac.uk/studying/undergraduate/",
    internationalAdmissionsUrl: "https://www.ed.ac.uk/studying/international/",
    scholarshipUrl: "https://www.ed.ac.uk/student-funding/scholarships/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.ed.ac.uk/studying/undergraduate/", label: "Edinburgh Admissions" }],
  },
  {
    name: "University of Manchester",
    country: "UK",
    city: "Manchester",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.manchester.ac.uk/study/",
    internationalAdmissionsUrl: "https://www.manchester.ac.uk/study/international/",
    scholarshipUrl: "https://www.manchester.ac.uk/study/undergraduate/fees-and-funding/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.manchester.ac.uk/study/", label: "Manchester Admissions" }],
  },
  {
    name: "King's College London",
    country: "UK",
    city: "London",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.kcl.ac.uk/study",
    internationalAdmissionsUrl: "https://www.kcl.ac.uk/study/international",
    scholarshipUrl: "https://www.kcl.ac.uk/study/funding",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.kcl.ac.uk/study", label: "KCL Admissions" }],
  },
  {
    name: "University of Bristol",
    country: "UK",
    city: "Bristol",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://www.bristol.ac.uk/study/",
    internationalAdmissionsUrl: "https://www.bristol.ac.uk/study/international/",
    scholarshipUrl: "https://www.bristol.ac.uk/students/support/finances/scholarships/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://www.bristol.ac.uk/study/", label: "Bristol Admissions" }],
  },
  {
    name: "University of Warwick",
    country: "UK",
    city: "Coventry",
    languages: ["en"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "high",
    admissionsUrl: "https://warwick.ac.uk/study/",
    internationalAdmissionsUrl: "https://warwick.ac.uk/study/international/",
    scholarshipUrl: "https://warwick.ac.uk/study/undergraduate/fees-funding/",
    requirements: { englishTests: ["TOEFL", "IELTS"], applicationPlatform: "UCAS" },
    tags: ["russell-group"],
    sources: [{ url: "https://warwick.ac.uk/study/", label: "Warwick Admissions" }],
  },

  // ── Dominican Republic ────────────────────────────────────────────────
  {
    name: "Pontificia Universidad Católica Madre y Maestra (PUCMM)",
    country: "DO",
    city: "Santiago de los Caballeros",
    languages: ["es"],
    levelSupport: ["bachelor", "master"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.pucmm.edu.do/admisiones/",
    scholarshipUrl: "https://www.pucmm.edu.do/becas/",
    requirements: { applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["caribbean", "spanish-language"],
    sources: [{ url: "https://www.pucmm.edu.do/admisiones/", label: "PUCMM Admissions" }],
  },
  {
    name: "Instituto Tecnológico de Santo Domingo (INTEC)",
    country: "DO",
    city: "Santo Domingo",
    languages: ["es"],
    levelSupport: ["bachelor", "master"],
    tuitionBand: "medium",
    admissionsUrl: "https://www.intec.edu.do/admisiones/",
    scholarshipUrl: "https://www.intec.edu.do/becas/",
    requirements: { applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["caribbean", "stem", "spanish-language"],
    sources: [{ url: "https://www.intec.edu.do/admisiones/", label: "INTEC Admissions" }],
  },
  {
    name: "Universidad Autónoma de Santo Domingo (UASD)",
    country: "DO",
    city: "Santo Domingo",
    languages: ["es"],
    levelSupport: ["bachelor", "master", "phd"],
    tuitionBand: "low",
    admissionsUrl: "https://www.uasd.edu.do/admisiones/",
    requirements: { applicationPlatform: "Direct" },
    haitianFriendly: true,
    tags: ["caribbean", "public", "affordable", "spanish-language"],
    sources: [{ url: "https://www.uasd.edu.do/admisiones/", label: "UASD Admissions" }],
  },
];

// ── Main ───────────────────────────────────────────────────────────────────
async function main() {
  console.log(`🏫 Seeding ${UNIVERSITIES.length} universities…\n`);

  let created = 0;
  let updated = 0;

  for (const uni of UNIVERSITIES) {
    const result = await universitiesRepo.upsertByName(uni);
    if (result.created) {
      created++;
      console.log(`  ✅  created  ${uni.name} (${uni.country})`);
    } else {
      updated++;
      console.log(`  ♻️  updated  ${uni.name} (${uni.country})`);
    }
  }

  console.log(`\n🏁 Done — created: ${created}, updated: ${updated}, total: ${UNIVERSITIES.length}`);
}

main().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
